#
# This file is part of BDC-Auth-Client.
# Copyright (C) 2020 INPE.
#
# BDC-Auth-Client is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

language: python

os: linux

cache:
    directories:
        - "$HOME/.cache/pip"

git:
    quiet: true
    submodules: false

branches:
    only:
        - master

dist: bionic

python:
    - '3.7'

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls
