#
# This file is part of BDC-Auth-Client.
# Copyright (C) 2019-2020 INPE.
#
# BDC-Auth-Client is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

[pytest]
addopts = --color=auto --cov=bdc_auth_client --cov-report=term-missing
testpaths = tests